title: idyog
author:
  name: Nicholas Harley
  email: nicholas.harley@vub.be
description:
This repository contains preliminary experiements investigating the use of statistical models to detect sub-task boundaries in data describing the behaviour of agents in minimalistic gridword environments.
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
show_downloads: "true"
theme: minima
minima:
  social_links: 
    github: n-harley
header_pages:
  - models.md	